name: CI Test and Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Check Python
        run: |
          python --version
          where python

      - name: Install dependencies
        run: |
          pip install pytest playwright Appium-Python-Client allure-pytest

      - name: Run Web Tests Only
        run: pytest tests/web/test_search_web.py --alluredir=allure-results

      - name: Debug Show current working directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "Listing files:"
          dir  # Windows / ls -al (Linux)

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: allure-results
          allure_report: allure-report
          keep_reports: 5

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Send Slack Notification
        run: |
          $payload = @{
            text = "*í…ŒìŠ¤íŠ¸ ì‹¤í–‰ ì™„ë£Œ* :white_check_mark:`në¸Œëœì¹˜: ${{ github.ref }}`nê²°ê³¼: ì„±ê³µ ğŸ‰`n[ë¦¬í¬íŠ¸ ë³´ê¸°](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          } | ConvertTo-Json -Compress

          Invoke-RestMethod `
            -Uri "${{ secrets.SLACK_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType 'application/json'


