name: CI Test and Report

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print workspace path
        run: echo "GitHub workspace - $env:GITHUB_WORKSPACE"

      - name: Check Python
        run: |
          python --version
          where python
        working-directory: ${{ github.workspace }}

      - name: Install dependencies
        run: |
          Set-Location $env:GITHUB_WORKSPACE
          # pip install pytest playwright Appium-Python-Client allure-pytest
          pip install -r requirements.txt

      - name: Run Web Tests Only
        run: |
          Set-Location $env:GITHUB_WORKSPACE
          pytest tests/web/test_search_web.py --alluredir=allure-results

      - name: Generate Allure Report
        run: |
          Set-Location $env:GITHUB_WORKSPACE
          allure generate --clean -o allure-report allure-results

      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Send Slack Notification
        run: |
          $payload = @{
            text = "*í…ŒìŠ¤íŠ¸ ì‹¤í–‰ ì™„ë£Œ* :white_check_mark:`në¸Œëœì¹˜: ${{ github.ref }}`nê²°ê³¼: ì„±ê³µ ğŸ‰`n[ë¦¬í¬íŠ¸ ë³´ê¸°](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})"
          } | ConvertTo-Json -Compress

          Invoke-RestMethod `
            -Uri "${{ secrets.SLACK_WEBHOOK_URL }}" `
            -Method Post `
            -Body $payload `
            -ContentType 'application/json'

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "í…ŒìŠ¤íŠ¸ ì‹¤í–‰ ì™„ë£Œ - ${{ github.ref }}"
          to: syjeong@wisewires.com
          from: "Automation Bot <ssyeon612@gmail.com>"
          body: |
            í…ŒìŠ¤íŠ¸ ì‹¤í–‰ì´ ì™„ë£Œë˜ì—ˆìŠµë‹ˆë‹¤.

            ë¸Œëœì¹˜: ${{ github.ref }}
            ê²°ê³¼: ì„±ê³µ ğŸ‰
            ë¦¬í¬íŠ¸ ë³´ê¸°: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
          keep_files: false

